-- ReferenceGear.lua
-- Endgame reference items per role group and slot, used to derive the
-- color references: an item shows red when it scores like expansion-endgame
-- BiS, because the reference IS a representative endgame item run through
-- the live scoring pipeline. This replaces hand-tuned score caps - if
-- weights, budget costs, or parsing change, the references move with them
-- automatically.
--
-- TBC values approximate Sunwell-tier (ilvl ~159-164) items including
-- typical gems. They are data, not code: tune individual slots here.
-- Other flavors fall back to the static caps until reference sets are added.

GSPlus = GSPlus or {}
GSPlus.ReferenceGear = GSPlus.ReferenceGear or {}

local ReferenceGear = GSPlus.ReferenceGear

ReferenceGear.REFERENCE_GEAR_BY_FLAVOR = {
    TBC = {
        CASTER_DPS = {
            INVTYPE_HEAD = { STAMINA = 45, INTELLECT = 40, SPELLPOWER = 75, CRITICAL = 38 },
            INVTYPE_NECK = { STAMINA = 25, INTELLECT = 22, SPELLPOWER = 40, CRITICAL = 21 },
            INVTYPE_SHOULDER = { STAMINA = 33, INTELLECT = 28, SPELLPOWER = 55, CRITICAL = 26 },
            INVTYPE_CLOAK = { STAMINA = 24, INTELLECT = 20, SPELLPOWER = 42, HASTE = 22 },
            INVTYPE_CHEST = { STAMINA = 45, INTELLECT = 40, SPELLPOWER = 75, HIT = 25, CRITICAL = 25 },
            INVTYPE_ROBE = { STAMINA = 45, INTELLECT = 40, SPELLPOWER = 75, HIT = 25, CRITICAL = 25 },
            INVTYPE_WRIST = { STAMINA = 20, INTELLECT = 18, SPELLPOWER = 37, CRITICAL = 18 },
            INVTYPE_HAND = { STAMINA = 32, INTELLECT = 28, SPELLPOWER = 55, CRITICAL = 27 },
            INVTYPE_WAIST = { STAMINA = 32, INTELLECT = 30, SPELLPOWER = 55, HIT = 21, CRITICAL = 20 },
            INVTYPE_LEGS = { STAMINA = 45, INTELLECT = 40, SPELLPOWER = 72, CRITICAL = 40 },
            INVTYPE_FEET = { STAMINA = 33, INTELLECT = 28, SPELLPOWER = 55, CRITICAL = 25 },
            INVTYPE_FINGER = { STAMINA = 22, INTELLECT = 20, SPELLPOWER = 40, HASTE = 20 },
            INVTYPE_TRINKET = { SPELLPOWER = 65, CRITICAL = 40 },
            INVTYPE_WEAPON = { STAMINA = 30, INTELLECT = 29, SPELLPOWER = 170, CRITICAL = 25, HASTE = 20 },
            INVTYPE_WEAPONMAINHAND = { STAMINA = 30, INTELLECT = 29, SPELLPOWER = 170, CRITICAL = 25, HASTE = 20 },
            INVTYPE_WEAPONOFFHAND = { STAMINA = 20, INTELLECT = 20, SPELLPOWER = 90, CRITICAL = 20 },
            INVTYPE_HOLDABLE = { STAMINA = 20, INTELLECT = 20, SPELLPOWER = 90, CRITICAL = 20 },
            INVTYPE_SHIELD = { STAMINA = 28, INTELLECT = 25, SPELLPOWER = 75 },
            INVTYPE_2HWEAPON = { STAMINA = 55, INTELLECT = 52, SPELLPOWER = 280, CRITICAL = 45, HIT = 30 },
            INVTYPE_RANGED = { STAMINA = 14, INTELLECT = 13, SPELLPOWER = 23, CRITICAL = 12 },
            INVTYPE_RANGEDRIGHT = { STAMINA = 14, INTELLECT = 13, SPELLPOWER = 23, CRITICAL = 12 },
            INVTYPE_THROWN = { STAMINA = 14, INTELLECT = 13, SPELLPOWER = 23 },
            INVTYPE_RELIC = { SPELLPOWER = 30 },
        },

        HEALER = {
            INVTYPE_HEAD = { STAMINA = 42, INTELLECT = 42, HEALING = 125, SPELLPOWER = 42, MP5 = 10, CRITICAL = 30 },
            INVTYPE_NECK = { STAMINA = 24, INTELLECT = 24, HEALING = 70, SPELLPOWER = 24, MP5 = 6 },
            INVTYPE_SHOULDER = { STAMINA = 32, INTELLECT = 30, HEALING = 92, SPELLPOWER = 31, MP5 = 7 },
            INVTYPE_CLOAK = { STAMINA = 23, INTELLECT = 22, HEALING = 66, SPELLPOWER = 22, MP5 = 6 },
            INVTYPE_CHEST = { STAMINA = 43, INTELLECT = 42, HEALING = 125, SPELLPOWER = 42, MP5 = 10, SPIRIT = 25 },
            INVTYPE_ROBE = { STAMINA = 43, INTELLECT = 42, HEALING = 125, SPELLPOWER = 42, MP5 = 10, SPIRIT = 25 },
            INVTYPE_WRIST = { STAMINA = 19, INTELLECT = 19, HEALING = 59, SPELLPOWER = 20, MP5 = 5 },
            INVTYPE_HAND = { STAMINA = 30, INTELLECT = 30, HEALING = 92, SPELLPOWER = 31, CRITICAL = 20 },
            INVTYPE_WAIST = { STAMINA = 30, INTELLECT = 31, HEALING = 92, SPELLPOWER = 31, MP5 = 8 },
            INVTYPE_LEGS = { STAMINA = 42, INTELLECT = 40, HEALING = 120, SPELLPOWER = 40, SPIRIT = 28, MP5 = 8 },
            INVTYPE_FEET = { STAMINA = 31, INTELLECT = 29, HEALING = 89, SPELLPOWER = 30, MP5 = 7 },
            INVTYPE_FINGER = { STAMINA = 20, INTELLECT = 22, HEALING = 73, SPELLPOWER = 25, MP5 = 5 },
            INVTYPE_TRINKET = { HEALING = 120, MP5 = 10 },
            INVTYPE_WEAPON = { STAMINA = 28, INTELLECT = 30, HEALING = 430, SPELLPOWER = 143, MP5 = 8 },
            INVTYPE_WEAPONMAINHAND = { STAMINA = 28, INTELLECT = 30, HEALING = 430, SPELLPOWER = 143, MP5 = 8 },
            INVTYPE_WEAPONOFFHAND = { STAMINA = 18, INTELLECT = 20, HEALING = 85, SPELLPOWER = 28, MP5 = 4 },
            INVTYPE_HOLDABLE = { STAMINA = 18, INTELLECT = 20, HEALING = 85, SPELLPOWER = 28, MP5 = 4 },
            INVTYPE_SHIELD = { STAMINA = 30, INTELLECT = 25, HEALING = 66, MP5 = 5 },
            INVTYPE_2HWEAPON = { STAMINA = 52, INTELLECT = 50, HEALING = 480, SPELLPOWER = 160, MP5 = 12 },
            INVTYPE_RANGED = { STAMINA = 13, INTELLECT = 13, HEALING = 40, MP5 = 3 },
            INVTYPE_RANGEDRIGHT = { STAMINA = 13, INTELLECT = 13, HEALING = 40, MP5 = 3 },
            INVTYPE_THROWN = { STAMINA = 13, INTELLECT = 13, HEALING = 40 },
            INVTYPE_RELIC = { HEALING = 50 },
        },

        -- Attackpower is a "cheap" budget stat, so endgame items carry more of
        -- it than the spellpower casters get; the reference reflects that, and
        -- carries ranged attackpower too so hunters (who weight it) aren't left
        -- below the other roles.
        PHYSICAL_DPS = {
            INVTYPE_HEAD = { AGILITY = 45, STAMINA = 40, ATTACKPOWER = 106, RANGED_ATTACKPOWER = 53, CRITICAL = 35, HIT = 20 },
            INVTYPE_NECK = { AGILITY = 25, STAMINA = 22, ATTACKPOWER = 65, RANGED_ATTACKPOWER = 32, CRITICAL = 20 },
            INVTYPE_SHOULDER = { AGILITY = 33, STAMINA = 30, ATTACKPOWER = 83, RANGED_ATTACKPOWER = 41, CRITICAL = 25 },
            INVTYPE_CLOAK = { AGILITY = 24, STAMINA = 20, ATTACKPOWER = 65, RANGED_ATTACKPOWER = 32, HIT = 15 },
            INVTYPE_CHEST = { AGILITY = 45, STAMINA = 42, ATTACKPOWER = 112, RANGED_ATTACKPOWER = 56, CRITICAL = 35, HIT = 18 },
            INVTYPE_ROBE = { AGILITY = 45, STAMINA = 42, ATTACKPOWER = 112, RANGED_ATTACKPOWER = 56, CRITICAL = 35, HIT = 18 },
            INVTYPE_WRIST = { AGILITY = 20, STAMINA = 18, ATTACKPOWER = 53, RANGED_ATTACKPOWER = 26, CRITICAL = 16 },
            INVTYPE_HAND = { AGILITY = 32, STAMINA = 30, ATTACKPOWER = 83, RANGED_ATTACKPOWER = 41, CRITICAL = 26 },
            INVTYPE_WAIST = { AGILITY = 32, STAMINA = 30, ATTACKPOWER = 83, RANGED_ATTACKPOWER = 41, CRITICAL = 25, HIT = 16 },
            INVTYPE_LEGS = { AGILITY = 44, STAMINA = 42, ATTACKPOWER = 112, RANGED_ATTACKPOWER = 56, CRITICAL = 38 },
            INVTYPE_FEET = { AGILITY = 32, STAMINA = 30, ATTACKPOWER = 80, RANGED_ATTACKPOWER = 40, CRITICAL = 25 },
            INVTYPE_FINGER = { AGILITY = 22, STAMINA = 18, ATTACKPOWER = 61, RANGED_ATTACKPOWER = 30, CRITICAL = 18 },
            INVTYPE_TRINKET = { ATTACKPOWER = 142, RANGED_ATTACKPOWER = 71, CRITICAL = 40 },
            INVTYPE_WEAPON = { AGILITY = 20, STAMINA = 18, ATTACKPOWER = 59, RANGED_ATTACKPOWER = 29, CRITICAL = 18, WEAPON_DPS = 112, WEAPON_AVERAGE_DAMAGE = 180 },
            INVTYPE_WEAPONMAINHAND = { AGILITY = 20, STAMINA = 18, ATTACKPOWER = 59, RANGED_ATTACKPOWER = 29, CRITICAL = 18, WEAPON_DPS = 112, WEAPON_AVERAGE_DAMAGE = 180 },
            INVTYPE_WEAPONOFFHAND = { AGILITY = 20, STAMINA = 18, ATTACKPOWER = 59, RANGED_ATTACKPOWER = 29, CRITICAL = 18, WEAPON_DPS = 112, WEAPON_AVERAGE_DAMAGE = 180 },
            INVTYPE_HOLDABLE = { STAMINA = 25, AGILITY = 15, ATTACKPOWER = 35, RANGED_ATTACKPOWER = 17 },
            INVTYPE_SHIELD = { STAMINA = 25, AGILITY = 15, ATTACKPOWER = 35, RANGED_ATTACKPOWER = 17 },
            INVTYPE_2HWEAPON = { STRENGTH = 50, AGILITY = 35, STAMINA = 45, ATTACKPOWER = 130, RANGED_ATTACKPOWER = 65, CRITICAL = 40, WEAPON_DPS = 175, WEAPON_AVERAGE_DAMAGE = 550 },
            INVTYPE_RANGED = { AGILITY = 18, STAMINA = 15, ATTACKPOWER = 47, RANGED_ATTACKPOWER = 23, CRITICAL = 16, WEAPON_DPS = 109, WEAPON_AVERAGE_DAMAGE = 300 },
            INVTYPE_RANGEDRIGHT = { AGILITY = 18, STAMINA = 15, ATTACKPOWER = 47, RANGED_ATTACKPOWER = 23, CRITICAL = 16, WEAPON_DPS = 109, WEAPON_AVERAGE_DAMAGE = 300 },
            INVTYPE_THROWN = { AGILITY = 18, STAMINA = 15, ATTACKPOWER = 47, RANGED_ATTACKPOWER = 23, CRITICAL = 16, WEAPON_DPS = 109, WEAPON_AVERAGE_DAMAGE = 300 },
            INVTYPE_RELIC = { ATTACKPOWER = 59, RANGED_ATTACKPOWER = 29 },
        },

        TANK = {
            INVTYPE_HEAD = { STAMINA = 65, DEFENSE = 35, DODGE = 30, AGILITY = 20, ARMOR = 1200 },
            INVTYPE_NECK = { STAMINA = 38, DEFENSE = 22, DODGE = 18 },
            INVTYPE_SHOULDER = { STAMINA = 48, DEFENSE = 25, DODGE = 20, ARMOR = 900 },
            INVTYPE_CLOAK = { STAMINA = 36, DEFENSE = 20, DODGE = 16, ARMOR = 300 },
            INVTYPE_CHEST = { STAMINA = 70, DEFENSE = 35, DODGE = 28, ARMOR = 1600 },
            INVTYPE_ROBE = { STAMINA = 70, DEFENSE = 35, DODGE = 28, ARMOR = 1600 },
            INVTYPE_WRIST = { STAMINA = 32, DEFENSE = 17, DODGE = 13, ARMOR = 550 },
            INVTYPE_HAND = { STAMINA = 48, DEFENSE = 24, DODGE = 18, ARMOR = 950 },
            INVTYPE_WAIST = { STAMINA = 48, DEFENSE = 25, BLOCK_VALUE = 35, ARMOR = 850 },
            INVTYPE_LEGS = { STAMINA = 70, DEFENSE = 33, DODGE = 28, ARMOR = 1400 },
            INVTYPE_FEET = { STAMINA = 47, DEFENSE = 24, DODGE = 18, ARMOR = 950 },
            INVTYPE_FINGER = { STAMINA = 40, DEFENSE = 20, DODGE = 15 },
            INVTYPE_TRINKET = { STAMINA = 55, DODGE = 35 },
            -- SPELLPOWER on tank weapons reflects a prot paladin's BiS threat
            -- weapon (spell power is their core threat stat). It only affects
            -- PALADIN_TANK: warrior/druid/DK tanks weight SPELLPOWER at 0, so it
            -- contributes nothing to their color reference.
            INVTYPE_WEAPON = { STAMINA = 30, DEFENSE = 18, DODGE = 15, EXPERTISE = 20, SPELLPOWER = 150, WEAPON_DPS = 95, WEAPON_AVERAGE_DAMAGE = 130 },
            INVTYPE_WEAPONMAINHAND = { STAMINA = 30, DEFENSE = 18, DODGE = 15, EXPERTISE = 20, SPELLPOWER = 150, WEAPON_DPS = 95, WEAPON_AVERAGE_DAMAGE = 130 },
            INVTYPE_WEAPONOFFHAND = { STAMINA = 30, DODGE = 15, SPELLPOWER = 60 },
            INVTYPE_HOLDABLE = { STAMINA = 30, DODGE = 15, SPELLPOWER = 60 },
            INVTYPE_SHIELD = { STAMINA = 45, BLOCK = 25, BLOCK_VALUE = 90, ARMOR = 6300 },
            INVTYPE_2HWEAPON = { STAMINA = 55, AGILITY = 35, ATTACKPOWER = 90, SPELLPOWER = 200, WEAPON_DPS = 170, WEAPON_AVERAGE_DAMAGE = 520 },
            INVTYPE_RANGED = { STAMINA = 20, DEFENSE = 10, AGILITY = 12 },
            INVTYPE_RANGEDRIGHT = { STAMINA = 20, DEFENSE = 10, AGILITY = 12 },
            INVTYPE_THROWN = { STAMINA = 20, DEFENSE = 10, AGILITY = 12 },
            INVTYPE_RELIC = { STAMINA = 30 },
        },
    },
}

function ReferenceGear:GetStats(groupName, equipLoc)
    local refs = GSPlus.GameVersion:Select(self.REFERENCE_GEAR_BY_FLAVOR)

    if not refs then
        return nil
    end

    local groupRefs = refs[groupName] or refs.CASTER_DPS

    return groupRefs and groupRefs[equipLoc]
end
